---
title: "Memory"
subtitle: 2025-12-09
fig-align: "center"
---

# Prelude

---

{{< video https://www.youtube.com/watch?v=5mlllRdIfqw width="100%" height="70%" >}}

-- @Timvitkuske2014-wy

## Announcements

## Today's topics

- Memory
- Quiz 4

# Memory

# Quiz 4

---

### 1. NMDA receptor binds which neurotransmitter?

- A. GABA 
- B. Norepinephrine
- C. Glutamate
- D. Dopamine 

---

### 2. Which of the following statements about the NMDA receptor is FALSE?

- A. It is ionotropic.
- B. It is metabotropic.
- C. It is voltage-gated.
- D. It binds glutamate.

---

### 3. Unlike computers, biological memories are stored in patterns of neuronal activations and synaptic strengths distributed across areas of the nervous system. 

- A. True
- B. False

---

### 4. The entry of what ion into the postsynaptic cell through NMDA receptors triggers long-term potentiation (LTP)?

- A. Cl- (chloride)
- B. Ca++ (calcium)
- C. Mg++ (magnesium)
- D. K+ (potassium)

---

### 5.

---

### 6.

---

### 7.

---

### 8.

---

### 9.

---

### 10.

---

### 11.

---

### 12.


# Point 2

# Wrap up

## Main points

## Next time

# Resources

## About

This talk was produced using [Quarto](https://quarto.org), using the [RStudio](https://posit.co/products/open-source/rstudio/)
Integrated Development Environment (IDE), version `r Sys.getenv("RSTUDIO_VER")`.

The source files are in R and R Markdown, then rendered to HTML using the
[revealJS](https://revealjs.com) framework. 
The HTML slides are hosted in a [GitHub repo](https://github.com/psu-psychology/psych-260-2025-fall) and served by GitHub pages: 
<https://psu-psychology.github.io/psych-260-2025-fall/>

## References
