---
title: "The Cerebral Symphony"
date: 2025-05-01
---

## The cerebral symphony

From very early on in teaching this course, I've enjoyed wrapping things up in a way that let's us all step back, reflect, and in some small way, try to put into perspective what an awesome privilege it is to spend 15 weeks studying the “Neurological Bases of Human Behavior.” 

So, put down your pens, close your notebooks, and laptops, and just listen. You might even want to close your eyes.

---

For some of you, I suspect that the material in this course, down to the very words we use every day, was new.  Perhaps there was more jargon than you'd expected. Maybe you felt that you couldn’t really see the psychology in all the biology.

Maybe you took this course to learn something about the mind, but at some point you stopped seeing it in the midst of all the neurotransmitters, neurons, and nuclei that command our attention.

---

You’re not alone in that feeling. If you catch us in an honest moment, we neuroscientists might just confess that some days we have no idea what we are doing. We have no clue how the brain REALLY works. It's an enormously difficult task for any one person to see how all of these complex parts fit together into a cohesive whole.

Just think about what your 86 billion neurons are doing right now.

---

Hundreds of millions of photoreceptors in your two retinas are processing a continuous stream of light, dividing it into short, medium and long wavelengths, and turning it into sequences of dynamic images of this classroom, your classmates, and your nutty professor. The tympanic membrane in your middle ear is vibrating with the multitude of frequencies generated by my voice, your own breathing, and today’s musical inspiration.  

---

At the same time, your somatosensory system is receiving information about temperature, pressure, perhaps even pain from receptors in your skin. Receptors in your joints and muscle fibers report the position and length of your limbs. Some portion of those 86 billion neurons are monitoring your levels of fluids and body fuels, still others your heart rate and blood pressure. Specialized neurons are monitoring your level of energy and arousal...which, at this point in the semester may be pretty low. All of these streams float upon the activity of neurons, as does the mental activity that arises from them.

---

A _single_ human nervous system contains more neurons than there are stars in many galaxies. And these radiant sources of thought and feeling are bound to one another by forces more powerful than gravity.

---

Given the immense scale and astonishing complexity of the nervous system, it is a natural question to ask whether it is even possible for the human mind to understand its own workings in any sort of satisfying or meaningful way. Are we forever limited to seeing the barest glimpses, here and there only shadows, falling well short of any real understanding?  

---

Put another way, can you or I even dream of putting together all of the pieces--the second messengers and ion channels, the neurotransmitters and enzymes, the neurons and glia, the nuclei and tracts, the gyri and sulci, and truly _see_ a whole living, breathing, behaving, conscious being?

The challenge may seem insurmountable, the idea unthinkable, perhaps even more so now than before you took this course.

---

To tell you the truth, I don't know whether it _is_ possible for a person to understand the human brain in a satisfying or deep way. No one has yet. We have had our Penfield’s and Hebb’s and Milner's and Hubel’s and Wiesel’s. But, neuroscience awaits its Newton or Einstein or Curie.

---

Still, when I think about the achievements of some of the greatest minds in human history in *other* domains of human innovation, I remain optimistic. 
A handful of extraordinary human beings have already shown us what it is like to have such a sweeping and penetrating understanding of human nature.

---

Ludwig von Beethoven was such a man.  

We are listening to the fourth and final movement of Beethoven's 9th symphony, written in the last years of Beethoven's life.

---

Beethoven was born in Bonn, Germany, in December 1770 into unremarkable circumstances. Legend holds that his father, Johann, was a violent and intemperate alcoholic who beat music lessons into his young son. Later scholars would wonder whether his father’s beatings contributed to Beethoven’s chronically poor health.

---

Despite his father's methods, Beethoven showed enormous musical promise from an early age.  His skills flowered under the tutelage of Haydn and Salieri. His gave his first public performance at 7. His published his first compositions at 10.  

At 17, Beethoven met Mozart, who later said of the encounter: "*Watch this lad.  Someday he will force the world to talk about him.*" Later that year, Beethoven’s mother died. When his father took solace in alcohol, Beethoven took charge of the care of his younger brothers.

---

From the earliest moments of his public career Beethoven developed a reputation as a virtuoso pianist and an impetuous personality. He was known as a brilliant composer, especially in improvisation. 

Today we think of classical music as deeply formal, but in those days, pianists were pitted against one another in head-to-head competitions. 
The goal was to see who could play more brilliantly, more imaginatively, more daringly.  

---

The thrill of this sort of combative musicianship suited Beethoven's personality perfectly.  As one author^[https://www.sheetmusicdaily.com/ludwig-van-beethoven-1770-1827/] put it, 

>Beethoven’s rivals always retired, bloodied, from such combat. While he made enemies of many pianists...the nobility flocked to hear him.

---

Not only was he in great demand to give live performances, but he was incredibly productive in composition.  

In all ways, Beethoven's future looked bright. 
But, slowly, at first imperceptibly, and then, later more noticeably, his life began to change in the cruelest possible way. 
Beethoven had long suffered a list of maladies-- diarrhea, abdominal pain, respiratory illness, and depression, and he was known for self-medicating with ample quantities of alcohol. 

---

But, more daunting than these obstacles, Beethoven began to lose the mental faculty more important to a composer and musician than any other single ability. 
Can any of us imagine? 
Can we fully comprehend how a person faced with such obstacles could find the courage to go on? 
A person whose entire existence derives from the world of sound...going...deaf.

---

At first, Beethoven himself could not easily face the cruel irony, he said:

*How can I, a musician, say to people "I am deaf!" I shall, if I can, defy this fate, even though there will be times when I shall be the unhappiest of God's creatures...I live only in music..."*^[https://www.musicweb-international.com/scott/scottbook/Chapter5.htm]

---

Beethoven’s hearing loss was progressive and irreversible. 
But, he continued to compose, and do so brilliantly, often working on more than one piece at a time.
Composition had always been a struggle for Beethoven.
But, against these new barriers he became further withdrawn. 
In a letter to his brothers he tried to explain.

---

*Though born with a fiery, active temperament, even susceptible to the diversions of society, I was soon compelled to isolate myself, to live life alone. If at times I tried to forget all this, oh, how harshly was I flung back by the doubly sad experience of my bad hearing. Yet it was impossible for me to say to people, "Speak Louder, shout, for I am deaf". Oh, how could I possibly admit an infirmity in the one sense which ought to be more perfect in me than others, a sense which I once possessed in the highest perfection, a perfection such as few in my profession enjoy or ever have enjoyed. – Oh I cannot do it.*^[https://www.nypl.org/blog/2020/04/14/beethoven-isolation-lessons]

---

By 1820, he was entirely deaf.  

It is at this time that Beethoven composed the 9th symphony, perhaps his most *infamous* work. 
I say infamous, because since its first performance, the 9th has sparked controversy. 
As you may know, the 9th took the basic symphonic form and extended it to an unusual length, adding vocal soloists, a chorus, and incorporating a popular melody from another composer that has now become its signature.  

---

Two hundred years later, it remains enormously popular. 
Some consider it the most beautiful piece of music ever composed. 
But here is what critics at the time said about it:

>I regret to say that it appeared to be made up of the strange, the ludicrous, the abrupt, the ferocious, and the screechy, with the slightest possible admixture, here and there, of an intelligible melody...The general impression it left on me is that of a concert made up of Indian warwhoops and angry wildcats.^[https://buttondown.email/craftbyzen/archive/musical-discontent/] (Providence, RI, 1868)

---

>Beethoven always sounds to me like the upsetting of bags of nails, with here and there an also dropped hammer.(--John Ruskin to John Brown, 1881)^[https://quotefancy.com/quote/1009697/John-Ruskin-Beethoven-always-sounds-to-me-like-the-upsetting-of-a-bag-of-nails-with-here]

---

>If the best critics and orchestras have failed to find the meaning of Beethoven's Ninth Symphony, we may well be pardoned if we confess our inability to find any. The Adagio certainly possessed much beauty, but the other movements, particularly the last, appeared to be an incomprehensible union of strange harmonies.  (Boston Daily Atlas, 1853)^[https://berkeleyhighjacket.com/column/classical-music-critics-on-l-beethoven/]

---

The 9th symphony had its first performance on May 7, 1824 in Vienna. 
Of course Beethoven's deafness prevented him from conducting the premiere, but he stood next to the conductor during the performance to indicate the proper tempo.  

---

Imagine for a moment that we are in the audience of that concert hall. Imagine attending the premiere of a symphony written by one of the greatest composers of all time.  

Imagine watching a desperate Beethoven trying desperately (and failing miserably) to keep the time. 
Imagine hearing a symphony that the composer himself had *never* actually heard, and would never *ever* hear, except in the chamber hall of his own imagination.

---

An observer at the premiere described the scene this way:

>The master, though placed in the midst of this confluence of music, heard nothing of it at all and was not even sensible of the applause at the end of his great work.  [He] continued standing with his back to the audience until Fraulien Ungher, who had sung the contralto part, turned him, or induced him to turn around and face the people, who were still clapping their hands and giving way to the greatest demonstrations of pleasure.^[https://fwsymphony.org/program-notes/beethoven-ludwig-van-symphony-no-9-in-d-minor-opus-125-choral]

---

>His turning round, and the sudden conviction thereby forced upon everybody that he had not done so before, because he could not hear what was going on, acted like an electric shock on all present, and a volcanic explosion of sympathy and admiration followed, which was repeated again and again, and seemed as if it would never end.^[https://fwsymphony.org/program-notes/beethoven-ludwig-van-symphony-no-9-in-d-minor-opus-125-choral]

Even members of the orchestra wept.

---

As much as we ourselves might be moved by this saga of creation, we might also ask what has this to do with our task in this course. 
How does the triumph of this legendary musical figure over adversity help us better comprehend the mind and brain?  

---

What Beethoven's contemporaries saw as quirks of artistic temperament might in modern times be seen--and treated--as symptoms of mental illness. 
On top of his deafness, was Beethoven depressed, bipolar, schizophrenic, or dissociative?
We can never know. 
We do know from a post-mortem autopsy that he died of liver failure due to alcohol poisoning, and he may have been a victim of lead poisoning, as well.

---

Even so, we might wonder how much of genius lies in thought, feeling, and behavior that looks like pathology to those of us never touched by muses so great.
Is our knowledge of the mind and brain so certain that we can confidently define the line between health and illness, between creative genius and treatable madness?

---

Might Beethoven's mental and physical afflictions have been central to his creative power?
And, beyond our own musical enthrallment, might Beethoven’s story also inform and educate us about the very task we set out to accomplish in this course--to learn about the mind and brain?

---

Isn't our task like Beethoven's?
Aren't students of science in some crude way composers, challenged to struggle against the limitations of our own ignorance? 
Don’t we seek to determine how the tiny building blocks of our subject, the notes, or in our case, neurons or neurotransmitters, should be put together to make...sensations
To understand how groups of neurons firing in synchrony make harmonies, how regions make melodies, and how the nervous system and body unite over time into concertos and ultimately symphonies?  

---

And, isn't our handicap the same as Beethoven's?
Are we not profoundly and completely deaf to much of the mind’s music? 

At times doesn't it seem impossibly difficult to see where the mind emerges from the miniscule and microscopic pieces that comprise it? 

Hasn't this course at times seemed to you like Beethoven's 9th symphony seemed to critics 100 years ago, "an incomprehensible union of strange harmonies?"  

---

Maybe that sense of confusion has led you to doubt that it is even possible for a person, *any* person to ever hear clearly the notes of the mental score?

Perhaps the task of understanding our own mind *is* beyond human ability. Perhaps we neuroscientists are engaged in a fruitless and impossible pursuit, destined for eternal ignorance and frustration.

But if there is one lesson students of science should never, ever forget, it is to be skeptical.

---

And...also...optimistic.

Notwithstanding the many worries of the present moment, and they are many...

If it is possible to develop and deploy highly effective vaccines for a deadly virus using completely novel methods in less than a year's time and save hundreds of thousands of lives, then many, many previously unimaginable (and unreservedly positive) things are possible.

---

And, if in the hearts of women and men lies the capacity to *imagine* a symphony like this...a roar of the human spirit unlike any other...then perhaps...just perhaps...it is possible that one day another person of Beethoven's genius and imagination and vision and resolve will arrive. Perhaps it will be one of you. 
That person will see in ways we do not, and hear in ways we cannot.

---

That person will feel “joy, the beautiful spark of the gods,” as this symphony’s chorus sings, and will “enter fire imbibed” with the awe of profound discovery.
That visionary will hear the song of our mind and brain, the magnificent cerebral symphony, in a way it has never been heard before.
That person, like Beethoven two centuries ago, will illuminate dark dimensions of the mind and brain that have stood before entirely in shadow.

---

And isn't it almost certain that the cerebral symphony that visionary future scientist hears and helps us to hear will sound as strange, and ludicrous, and ferocious, and incomprehensible, and tearful, and....joyful as Beethoven's 9th symphony did to 19th century audiences?

---

To teach is to hope. And from hope springs belief.

---

I *hope* that that the insight and courage needed to help us understand our own natures and truly hear how brain makes mind is **not** beyond human capacity.  

I *believe* that some person some day will make plain facts about the brain that now appear utterly incomprehensible.
That knowledge will help us peer deep into the human imagination, just like Beethoven's symphony and offer up a gift to the fullness of the human spirit.

---

It will be...an ode to joy.

---

Be well, do great work, take good care, and keep in touch.
