---
title: "Exam II review"
subtitle: 2025-10-21
fig-align: "center"
engine: knitr
---

## Today's topics

- Warm-up
- Exam 2 review

# Warm-up

## Which of the following phases of human brain development extends into early adulthood?

::: {.incremental}
- A. Cortical neurogenesis
- B. Apoptosis (cell death)
- D. Neurulation (formation of neural tube)
- E. Myelination

:::

## Which of the following phases of human brain development extends into early adulthood?

- ~~A. Cortical neurogenesis~~
- ~~B. Apoptosis (cell death)~~
- ~~D. Neurulation (formation of neural tube)~~
- **E. Myelination**

## Where in the CNS do most neurons and glial cells originate?

::: {.incremental}
- A. Cell layers near the cerebral ventricles
- B. Blood vessels
- D. Meninges
- E. Cerebrospinal fluid (CSF)
:::

## Where in the CNS do most neurons and glial cells originate?

- **A. Cell layers near the cerebral ventricles**
- ~~B. Blood vessels~~
- ~~D. Meninges~~
- ~~E. Cerebrospinal fluid (CSF)~~

## Synapses form starting in prenatal life and extending throughout the lifespan.

- True
- False

## Synapses form starting in prenatal life and extending throughout the lifespan.

- **True**
- ~~False~~

# Exam 2 topics

## Methods

- Structural vs. functional MRI methods

## Action potential

- Steps in...

## Synaptic transmission

- Steps in...
- Ionotropic, metabotropic receptors
- EPSPs, IPSPs
- Gap junctions

## Neurotransmitters

- Glutamate, GABA, acetylcholine
- Monoamines: Dopamine, Norepinephrine, Serotonin, Melatonin, Histamine
- How inactivated
  - Serotonin
  - Acetylcholine

## Hormones

- Melatonin
- Oxytocin
- Hypothalamic Pituitary Adrenal (HPA) axis

## Hormones

- Adrenal gland
  - Cortisol
  - Epinephrine, Norepinehphrine
- Sympathetic Adrenal Medulla (SAM) axis

## Evolution

- When vertebrate nervous systems emerged
- Relative size, neuron number in cerebellum vs. cerebral cortex
- Radial vs. bilateral symmetry
- Brain mass vs. body mass

## Development

- Neural tube formation

## Neuroanatomy

- Pineal gland
- Hypothalamus
- Pituitary gland
  - Anterior
  - Posterior
  
## Neuroanatomy

- Ventral tegmental area
- Sympathetic nervous system
- Parasympathetic nervous system

## Neuroanatomy

- Lateral fissure
- Frontal lobe, parietal lobe

## Cellular neuroscience

- Microglia

# Wrap-up

## Next time

- Exam 2

# Resources

## About

This talk was produced using [Quarto](https://quarto.org), using the [RStudio](https://posit.co/products/open-source/rstudio/) Integrated Development Environment (IDE), version `r Sys.getenv("RSTUDIO_VER")`.

The source files are in R and R Markdown, then rendered to HTML using the [revealJS](https://revealjs.com) framework.
The HTML slides are hosted in a [GitHub repo](https://github.com/psu-psychology/psych-260-2025-fall) and served by GitHub pages:
<https://psu-psychology.github.io/psych-260-2025-fall/>

## References
