project:
  type: book
  output-dir: ../docs
  render:
  - "./*.qmd"
  - "slides/*.qmd"

book:
  title: "PSYCH 260.001"
  author: "Rick Gilmore"
  date: today
  chapters:
    - index.qmd
    - schedule.qmd
    - evaluation.qmd
    - deadlines.qmd
    - policies.qmd
  repo-url: https://github.com/psu-psychology/psych-260-2025-fall
  repo-actions: [edit, issue]
  repo-subdir: src
  page-footer:
    left: "Copyright © Rick Gilmore • [CC BY 4.0](https://creativecommons.org/licenses/by/4.0/)"
    center: "Built with [Quarto](https://quarto.org/)"
    right: 
      - icon: github
        href: https://github.com/psu-psychology/psych-260-2025-fall
    background: light
    border: true
  page-navigation: true
  bread-crumbs: false
  reader-mode: false

bibliography: [include/bib/psych-260.bib]
csl: include/bib/apa.csl

format:
  html:
    theme: [cosmo, include/css/psu.scss]
    mainfont: roboto
    fontsize: 1.1em
    toc: true
    toc-depth: 4
    fig-align: center
    number-sections: false
    citations-hover: true
    footnotes-hover: true
    link-external: true
    code-tools: true
    code-fold: true
    date-modified: last-modified
    date: today
    html-math-method: mathjax

  pdf:
    documentclass: scrreprt
  # epub:
  #   cover-image: include/img/childrens-thinking.jpg