# project:
#   type: book
#   output-dir: ../docs
#   render:
#     - "slides/*.qmd"
#     - "*.qmd"
#   lib-dir: include/site_libs

project:
  type: website
  output-dir: ../docs
  render:
    - "slides/*.qmd"
    - "*.qmd"
  lib-dir: include/site_libs
  
execute:
  freeze: auto

# book:
#   title: "PSYCH 260.001"
#   author: "Rick Gilmore"
#   date: today
#   chapters:
#     - index.qmd
#     - schedule.qmd
#     - evaluation.qmd
#     - deadlines.qmd
#     - policies.qmd
#   repo-url: https://github.com/psu-psychology/psych-260-2025-fall
#   repo-actions: [edit, issue]
#   repo-subdir: src
#   page-footer:
#     left: "Copyright © Rick Gilmore • [CC BY 4.0](https://creativecommons.org/licenses/by/4.0/)"
#     center: "Built with [Quarto](https://quarto.org/)"
#     right: 
#       - icon: github
#         href: https://github.com/psu-psychology/psych-260-2025-fall
#     background: light
#     border: true
#   page-navigation: true
#   bread-crumbs: false
#   reader-mode: false

website:
  title: "PSYCH 260.001"
  sidebar:
    style: "docked"
    search: true
    contents:
      - index.qmd
      - schedule.qmd
      - evaluation.qmd
      - deadlines.qmd
      - policies.qmd
      - section: "Slides"
        contents:
          - text: "Wk 01 • Tue Aug 26"
            href: slides/wk-01-2025-08-26-intro.qmd
  repo-url: https://github.com/psu-psychology/psych-260-2025-fall
  repo-actions: [edit, issue]
  repo-subdir: src
  page-footer:
    left: "Copyright © Rick Gilmore • [CC BY 4.0](https://creativecommons.org/licenses/by/4.0/)"
    center: "Built with [Quarto](https://quarto.org/)"
    right: 
      - icon: github
        href: https://github.com/psu-psychology/psych-260-2025-fall
    background: light
    border: true
  page-navigation: true
  bread-crumbs: false
  reader-mode: false
  
bibliography: [include/bib/psych-260.bib]
csl: include/bib/apa.csl

format:
  html:
    theme: [cosmo, include/css/psu.scss]
    mainfont: roboto
    fontsize: 1.1em
    toc: true
    toc-depth: 4
    fig-align: center
    number-sections: false
    citations-hover: true
    footnotes-hover: true
    link-external: true
    code-tools: true
    code-fold: true
    date-modified: last-modified
    date: today
    html-math-method: mathjax

  pdf:
    documentclass: scrreprt